Add support for AzureOpenAI
RedisVentures/redisvl pull request #131
Opened 2024-03-21 18:13 UTC by ajac-zero

**Objetive**

Added a new TextVectorizer for the AzureOpenAI API, which is based on the AzureOpenAI and AsyncAzureOpenAI classes from openai>=1.0.0.

**Reason**

Compatibility with Azure OpenAI is an important feature for developers that are building enterprise AI applications with Azure Cloud. Particularly for use cases where privacy is a concern, and data must stay within their cloud tenant.

My team particularly wants to integrate Semantic Cache (with Azure Cache for Redis Enterprise). Since we rely on the Azure OpenAI API, I created this new vectorizer to add that functionality.

2024-03-21 19:29 UTC, tylerhutcherson commented
@ajac-zero thanks for opening this -- will take a look and we will definitely get this in soon.

2024-04-04 20:15 UTC, tylerhutcherson requested changes
Thanks for this contribution! Will you please add tests for this (there are tests for other vectorizers you can follow along) and also a small addition to the docs `user_guide` for vectorizers. Thanks!

2024-04-19 23:39 UTC, ajac-zero commented
Sure! I've added the Azure vectorizer to the vectorizer test loop and a new section for Azure OpenAI in the vectorizers notebook.

All vectorizer tests pass with the Azure OpenAI vectorizer.
![image](https://github.com/RedisVentures/redisvl/assets/115488250/30c5fb0b-9994-4a5a-b12d-ecbeef3b5cd0)

2024-04-24 15:54 UTC, tylerhutcherson requested changes
So close! Left one small typo comment, then I will merge. I will fast follow with a commit to add the env vars to our github actions scripts.

2024-04-24 15:54 UTC, tylerhutcherson commented on redisvl/utils/vectorize/text/azureopenai.py
> +                "api_key": "your_api_key", # OR set OPENAI_API_KEY in your env
```suggestion
                "api_key": "your_api_key", # OR set AZURE_OPENAI_API_KEY in your env
```

2024-04-25 20:48 UTC, tylerhutcherson approved these changes

2024-04-25 20:55 UTC, merged